- name: events_list
    label: Church Events & Schedule
    type: file
    path: events.json
    format: json
    fields:
      - name: schedule
        label: Weekly Service Schedule
        type: object
        list: true
        fields:
          - name: day
            label: Day of Week
            type: string
          - name: title
            label: Service Name
            type: string
          - name: time
            label: Time
            type: string
          - name: description
            label: Short Description
            type: string

      - name: events
        label: Upcoming Special Events
        type: object
        list: true
        fields:
          - name: title
            label: Event Title
            type: string
          - name: date
            label: Date & Time
            type: string
          - name: description
            label: Description
            type: text
          - name: image
            label: Event Flyer
            type: image