media: assets/images
public_path: /assets/images

content:
  - name: pages
    label: Website Pages
    type: collection
    path: /
    view:
      fields: [title]
    fields:
      - name: title
        label: Page Title
        type: string
      - name: intro
        label: Main Text
        type: text
